(ns reframe.pages.tasks.view)

(def menu
  [[:div "Tasks Menu 1"]
   [:div "Tasks Menu 2"]
   [:div "Tasks Menu 3"]])

(defn page []
  [:div
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   [:div "Line"]
   ])
